baseURL = 'https://myuanzhang.github.io/'
languageCode = 'en-us'
title = 'Hello~'

theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowToc = true

[author]
  name = "Hello"  # 你可以修改为你的昵称
  email = "mrzhangmy1@gmail.com" # 你可以修改为你的邮箱，或者留空字符串 ""
