baseURL = 'https://myuanzhang.github.io/'
languageCode = 'en-us'
title = 'Hello~'

theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowToc = true

[params.author]
  name = "Myuanzhang"
  email = "mrzhangmy1@gmail.com"
